<?php echo $this->doctype() ?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Zend Framework Quickstart Application</title>
    <?php

     $this->headLink()->appendStylesheet($this->baseUrl(). '/css/bootstrap.css');
     $this->headScript()->prependFile($this->baseUrl().'/js/jquery/jquery-1.12.2.min.js');

    echo $this->headLink();
    echo $this->headScript();

    ?>
</head>
<body>
<div id="header" style="background-color: #b5d2ee; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>ZF Quickstart Application</b>
    </div>
</div>
<div class="container">
    <?php echo $this->layout()->content ?>
</div>
</body>
</html>