<?php echo $this->doctype() ?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <?php
    echo $this->headTitle("Typowanie");
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/bootstrap.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/style.css');
    $this->headScript()->prependFile($this->baseUrl() . '/js/jquery/jquery-1.12.2.min.js');
    $this->headScript()->appendFile($this->baseUrl().'/js/frontend.js', 'text/javascript');

    echo $this->headLink();
    echo $this->headScript();

    ?>
</head>
<body>
<div class="page-header">
    <h1 class="text-center">Aplikacja do typowania</h1>
</div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            nav panel
        </div>
        <?php echo $this->layout()->content ?>
    </div>
</div>
</body>
</html>